### ISSUE TITLE
ObjectDisposedException thrown if a request is inflight when configuration is reloaded

### ISSUE THREAD

**Issue by martincostello** [App-vNext/Polly#1578]
Testing out Polly `8.0.0-beta.1` in an internal production application, we have observed the following exception thrown when using a resilience strategy occur if the application's configuration is reloaded while the policy is in use.

```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'CircuitStateController'.
   at Polly.CircuitBreaker.CircuitStateController`1.EnsureNotDisposed()
   at Polly.CircuitBreaker.CircuitStateController`1.OnActionSuccessAsync(Outcome`1 outcome, ResilienceContext context)
   at Polly.CircuitBreaker.CircuitBreakerResilienceStrategy`1.ExecuteCore[TState](Func`3 callback, ResilienceContext context, TState state)
   at Polly.Utils.Pipeline.BridgeComponent`1.<ConvertValueTask>g__ConvertValueTaskAsync|5_0[TTo](ValueTask`1 valueTask, ResilienceContext resilienceContext)
   at Polly.Utils.Pipeline.CompositeComponent.ExecuteCoreWithTelemetry[TResult,TState](Func`3 callback, ResilienceContext context, TState state)
   at Polly.Utils.StrategyHelper.<ExecuteCallbackSafeAsync>g__AwaitTask|0_0[TResult,TState,T](ValueTask`1 task, Boolean continueOnCapturedContext)
   at Polly.Outcome`1.GetResultOrRethrow()
   at Polly.ResiliencePipeline.ExecuteAsync[TResult](Func`2 callback, ResilienceContext context)
   at MyApplication.Providers.ApiClient.ExecuteAsync[TResult](String rateLimitToken, String operationKey, ClientExecuteOptions`1 clientExecuteOptions, Func`3 action, CancellationToken cancellationToken) in /_/src/MyApplication/Providers/ApiClient.cs:line 186
   at MyApplication.Providers.ApiClient.ExecuteAsync[T](String rateLimitToken, String operationKey, Func`2 func, ClientExecuteOptions`1 clientExecuteOptions, CancellationToken cancellationToken) in /_/src/MyApplication/Providers/ApiClient.cs:line 125
   at MyApplication.Providers.InflightClient.GetByOrderIdAsync(String tenant, String orderId, CancellationToken cancellationToken, Boolean handleExecutionFaults) in /_/src/MyApplication/Providers/InflightClient.cs:line 74
   at MyApplication.Services.StatusService.GetOrderStatusAsync(String tenant, String id, CancellationToken cancellationToken) in /_/src/MyApplication/Services/StatusService.cs:line 109
   at MyApplication.Controllers.StatusController.GetStatusAsync(String tenant, String id, CancellationToken cancellationToken) in /_/src/MyApplication/Controllers/StatusController.cs:line 143
   at MyApplication.Controllers.StatusController.GetStatusByOrderIdAuthorized(String tenant, String id, CancellationToken cancellationToken) in /_/src/MyApplication/Controllers/StatusController.cs:line 96
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

I can't share the application code, but the overall structure is very similar to https://github.com/martincostello/polly-sandbox/pull/1.

Over a pool of 6 EC2 instances handling ~8,500 requests per minute between them at the time, we had 2 occurrences, so imagine there's an element of chance to whether or not it happens when the application is under load when the configuration is reloaded.

**Comment by martincostello** [comment]
Just found a second cluster of 3 of the same exception in another environment with a similar load and number of instances in service.

**Comment by martintmk** [comment]
I was worried this might happen. The solution is to keep track of active executions in circuit breaker and delay the disposal until the pipeline serves no more executions.
