### ISSUE TITLE
Advice Requested - NullReference on PolicyBuilder.OrSyntax

### ISSUE THREAD

**Issue by tomkerkhove** [App-vNext/Polly#204]
I'm currently building an infrastructure with Retry & Circuit Breaker but unfortunately I'm getting the `NullReferenceException` in `PolicyBuilder.OrSyntax.cs:line 79` and I'm trying to understand what I'm doing wrong.

**StackTrace:**
>    at Polly.PolicyBuilder`1.<>c__DisplayClass14_0.<OrResult>b__0(TResult result) in C:\projects\polly\src\Polly.Shared\PolicyBuilder.OrSyntax.cs:line 79
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Polly.Retry.RetryEngine.<ImplementationAsync>d__1`1.MoveNext() in C:\projects\polly\src\Polly.Shared\Retry\RetryEngineAsync.cs:line 34
--- End of stack trace from previous location where exception was thrown ---
   at Polly.Retry.RetryEngine.<ImplementationAsync>d__1`1.MoveNext() in C:\projects\polly\src\Polly.Shared\Retry\RetryEngineAsync.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Polly.Policy`1.<ExecuteAsync>d__15.MoveNext() in C:\projects\polly\src\Polly.Shared\ContextualPolicyAsync.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[Truncated]

# How we use it

I'm chaining the policies as following :
`await retryPolicy.ExecuteAsync(async () => await circuitBreakerPolicy.ExecuteAsync(communicationFunc, continueOnCapturedContext: true));`

_Note: I'm aware of the new `PolicyWrap` but we're not using it yet_

For the `circuitBreakerPolicy` we create it as following:
```
var circuitBreakerPolicy =  Policy.HandleResult(resultPredicate)
                                  .Or<TimeoutException>()
                                  .CircuitBreakerAsync(handledEventsBeforeBreaking, durationOfBreak, OnCircuitBroken, OnCircuitReset, OnCircuitHalfOpen);
```
For the `retryPolicy` we create it as following:
```
retryPolicy= Policy.HandleResult(resultPredicate)
                   .Or<TimeoutException>()
                   .WaitAndRetryAsync(retries.GetValueOrDefault(), i => TimeSpan.FromMilliseconds(millisecondsToWait.GetValueOrDefault()), (result, waitSpan) => // something });
```

Is there something I'm doing wrong or anything that can be improved?

**Comment by reisenberger** [comment]
Hi @tomkerkhove 
The stack trace of the `NullReferenceException` points at: https://github.com/App-vNext/Polly/blob/master/src/Polly.Shared/PolicyBuilder.OrSyntax.cs#L79

The stack trace suggests `resultPredicate` is `null` when the retry policy comes to evaluate retry conditions, which suggests `resultPredicate` was null when configuring the policy with:

`retryPolicy= Policy.HandleResult(resultPredicate)`

Does this help?

**Comment by tomkerkhove** [comment]
I'm currently at the "I'm a moron"-stage.
I went through the same steps like you've mentioned but overlooked the actual issue.

Thanks for pointing it out to me, I really appreciate it!
