### ISSUE TITLE
"Unable to cast object of type Polly.Retry.RetryPolicy to type Polly.Async Policy" exception is raised

### ISSUE THREAD

**Issue by Arash-Sabet** [App-vNext/Polly#493]
**Summary**: 
In an asp.net core 2.1 app, all services are wired up successfully when no Polly Policy is registered with policy registry. After defining a policy and getting it registered with registry per the following code snippet, calling  ```services.BuildServiceProvider().GetService<IMyInterface>()``` raises the exception mentioned in the title of this ticket/issue.

``` csharp
var policyRegistry= services.AddPolicyRegistry();
var policyKey = "samplepolicy";
var exceptionRetryPolicy = Policy
     .Handle<OperationCanceledException>()								
    .WaitAndRetryAsync(3, _ => TimeSpan.FromMilliseconds(50));

policyRegistry.Add(policyKey, exceptionRetryPolicy);
return httpClientBuilder.AddPolicyHandlerFromRegistry(policyKey);
```

<br/>
<br/>

**Expected behavior**: 
The exception should not take place.
<br/>
<br/>

**Actual behaviour**:
The exception happens per the following stack trace:

```
2018-08-21 11:05:54.390 -04:00 [FTL] Application startup exception
System.InvalidCastException: Unable to cast object of type 'Polly.Retry.RetryPolicy' to type 'Polly.IAsyncPolicy`1[System.Net.Http.HttpResponseMessage]'.
   at Polly.Registry.PolicyRegistry.Get[TPolicy](String key) in C:\projects\polly\src\Polly.Shared\Registry\PolicyRegistry.cs:line 62
   at Microsoft.Extensions.DependencyInjection.PollyHttpClientBuilderExtensions.<>c__DisplayClass3_0.<AddPolicyHandlerFromRegistry>b__0(IServiceProvider services)
   at Microsoft.Extensions.DependencyInjection.HttpClientBuilderExtensions.<>c__DisplayClass3_1.<AddHttpMessageHandler>b__2(HttpMessageHandlerBuilder b)
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.<>c__DisplayClass15_0.<CreateHandlerEntry>g__Configure|0(HttpMessageHandlerBuilder b)
   at Microsoft.Extensions.Http.LoggingHttpMessageHandlerBuilderFilter.<>c__DisplayClass2_0.<Configure>b__0(HttpMessageHandlerBuilder builder)
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateHandlerEntry(String name)
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.<>c__DisplayClass13_0.<.ctor>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateClient(String name)
   at Microsoft.Extensions.DependencyInjection.HttpClientBuilderExtensions.<>c__DisplayClass9_0`1.<AddTypedClient>b__0(IServiceProvider s)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
```

**Comment by reisenberger** [comment]
Hi @Arash-Sabet .  Policies used with `IHttpClientFactory` [must be policies handling `HttpResponseMessage`, of type `IAsyncPolicy<HttpResponseMessage>`](https://github.com/App-vNext/Polly/wiki/Polly-and-HttpClientFactory#using-any-policy-configured-via-the-traditional-polly-syntax).  

You can amend your configuration code either as:

```c#
    var exceptionRetryPolicy = Policy<HttpResponseMessage>
        .Handle<OperationCanceledException>()								
        .WaitAndRetryAsync(3, _ => TimeSpan.FromMilliseconds(50));
```

or, per the note in the above-linked wiki page, use the `.AsAsyncPolicy<HttpResponseMessage>()` extension method:

```c#
    policyRegistry.Add(policyKey, exceptionRetryPolicy).AsAsyncPolicy<HttpResponseMessage>());
```

Let us know if this resolves the issue.

**Comment by Arash-Sabet** [comment]
Thanks @reisenberger . It resolved the issue and hence I am closing this issue.
