### ISSUE TITLE
6.1.1 broke async CachePolicy with Polly.Caching.Memory 2.0.0

### ISSUE THREAD

**Issue by cmeeren** [App-vNext/Polly#539]
**Summary**: 

When upgrading from 6.1.0 to 6.1.1, caching is broken. `onCacheGetError` is called with ``System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<!!0> Polly.Utilities.TaskHelper.FromResult(!!0)'.``

**Steps / Code to reproduce the problem**: 

Repro solution: [Repro.zip](https://github.com/App-vNext/Polly/files/2599346/Repro.zip)

Code from repro solution, for easy reference:

```f#
open System
open System.Threading.Tasks
open Microsoft.Extensions.Caching.Memory
open Polly
open Polly.Caching.Memory

let cache =
  Policy.CacheAsync(
    MemoryCacheProvider(new MemoryCache(MemoryCacheOptions())),
    TimeSpan.FromMinutes 30.,
    (fun ctx s -> printfn "GET %s" s),
    (fun ctx s -> printfn "MISS %s" s),
    (fun ctx s -> printfn "PUT %s" s),
    (fun ctx s ex -> printfn "GETERR %s: %O" s ex),
    (fun ctx s ex -> printfn "PUTERR %s: %O" s ex)
  )

let f () =
  printfn "Inner function called"
  Task.FromResult ""

let fCached () =
  cache.ExecuteAsync((fun _ -> f ()), Context("cacheKey"))

[<EntryPoint>]
let main argv =
  fCached().Wait()
  printfn ""
  fCached().Wait()
  Console.ReadLine() |> ignore
  0
```

**Expected behavior**: 

```
MISS cacheKey
Inner function called
PUT cacheKey

GET cacheKey
```

**Actual behaviour**:

```
GETERR cacheKey: System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<!!0> Polly.Utilities.TaskHelper.FromResult(!!0)'.
   at Polly.Caching.Memory.MemoryCacheProvider.GetAsync(String key, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Polly.Caching.GenericCacheProviderAsync`1.Polly.Caching.IAsyncCacheProvider<TCacheFormat>.GetAsync(String key, CancellationToken cancellationToken, Boolean continueOnCapturedContext) in C:\projects\polly\src\Polly.Shared\Caching\GenericCacheProviderAsync.cs:line 22
   at Polly.Caching.CacheEngine.ImplementationAsync[TResult](IAsyncCacheProvider`1 cacheProvider, ITtlStrategy`1 ttlStrategy, Func`2 cacheKeyStrategy, Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext, Action`2 onCacheGet, Action`2 onCacheMiss, Action`2 onCachePut, Action`3 onCacheGetError, Action`3 onCachePutError) in C:\projects\polly\src\Polly.Shared\Caching\CacheEngineAsync.cs:line 0
MISS cacheKey
Inner function called
PUT cacheKey

<repeated for second call>
```

**Comment by reisenberger** [comment]
@cmeeren This should be fixed by: https://github.com/App-vNext/Polly.Caching.MemoryCache/pull/29 . (You are welcome to pull that PR down locally and test for yourself.)

Given we are in ThanksGiving week, Polly.Caching.Memory v2.0.1 may not publish to nuget for a few days, but the fix is done.

Thanks again for alerting this.
