### ISSUE TITLE
AdvanceCircuitBreaker with exception and status code

### ISSUE THREAD

**Issue by abdulwaheed05** [App-vNext/Polly#641]
Is there a way to configure the same circuit breaker policy with HttpRequestException and status codes of 503 Service Unavailable?

We tried this but it throws and exception when an HttpRequestException is received instead of a response message.

    Policy.HandleResult<HttpResponseMessage>(r => r.StatusCode == HttpStatusCode.ServiceUnavailable)                                                                       
        .Or<HttpRequestException>()
        .AdvancedCircuitBreakerAsync(circuitBreakerFailurePecentage, circuitBreakerSamplingDuration, circuitBreakerMinimumThroughput, circuitBreakerCoolingPeriod)

_(edited for code layout)_

**Comment by reisenberger** [comment]
@abdulwaheed05 The code you quoted should correctly configure a policy to handle both an `HttpRequestException` or 503 Service Unavailable.

It sounds as if the endpoint called may be mapping the 503 Service Unavailable to `HttpRequestException`.  A common cause of this is if the endpoint/code called uses [`HttpResponseMessage.EnsureSuccessStatusCode()`](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpresponsemessage.ensuresuccessstatuscode). Perhaps the system you are calling is doing that?

Here is the simplest of dotnetfiddle examples showing the Handle syntax you quoted works for this : https://dotnetfiddle.net/47Adc9

**Comment by abdulwaheed05** [comment]
@reisenberger thanks for the quick response. i am seeing below error with that code. we are using version 5.

System.NullReferenceException: Object reference not set to an instance of an object.
  X:\bt\1011566\repo\src\Common\Gateway\GatewayService\PolicyProvider.cs:line 73
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Polly.CircuitBreaker.CircuitBreakerEngine.<ImplementationAsync>d__1`1.MoveNext() in C:\projects\polly\src\Polly.Shared\CircuitBreaker\CircuitBreakerEngineAsync.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Polly.Policy`1.<ExecuteAsync>d__15.MoveNext() in C:\projects\polly\src\Polly.Shared\ContextualPolicyAsync.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  ....Some Stack Trace Removed....
   at Polly.Policy.<>c__DisplayClass55_0`1.<<ExecuteAsync>b__0>d.MoveNext() in C:\projects\polly\src\Polly.Shared\ContextualPolicyAsync.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Polly.RetrySyntaxAsync.<>c__DisplayClass5_0.<<RetryAsync>b__1>d.MoveNext() in C:\projects\polly\src\Polly.Shared\Retry\RetrySyntaxAsync.cs:line 116
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Polly.Retry.RetryEngine.<ImplementationAsync>d__1`1.MoveNext() in C:\projects\polly\src\Polly.Shared\Retry\RetryEngineAsync.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Polly.Retry.RetryEngine.<ImplementationAsync>d__1`1.MoveNext() in C:\projects\polly\src\Polly.Shared\Retry\RetryEngineAsync.cs:line 26
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Polly.Policy.<ExecuteAsync>d__55`1.MoveNext() in C:\projects\polly\src\Polly.Shared\ContextualPolicyAsync.cs:line 352
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by reisenberger** [comment]
@abdulwaheed05 With Polly v5.9.0 or Polly v7, I am not seeing a `NullReferenceException` with [this dotnetfiddle](https://dotnetfiddle.net/lRZLfY), where the endpoint instead throws `HttpRequestException`.  It handles the retries correctly.

Can you provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) demonstrating your problem case, please? 

Or at a minimum: Can you quote the declarations of all policies which govern the calls, how they are combined in a `PolicyWrap` if relevant, and what the actual call through the policy looks like?

Thanks

---

Looking at the stated code:

    Policy.HandleResult<HttpResponseMessage>(r => r.StatusCode == HttpStatusCode.ServiceUnavailable)                                                                       
        .Or<HttpRequestException>()
        .AdvancedCircuitBreakerAsync(circuitBreakerFailurePecentage, circuitBreakerSamplingDuration, circuitBreakerMinimumThroughput, circuitBreakerCoolingPeriod)

the obvious candidate for a `NullReferenceException` would be `r == null` at `r.StatusCode`. So you could simply change to `r => r?.StatusCode == HttpStatusCode.ServiceUnavailable`.  However, it is still unexpected to see `NullReferenceException` in the case of an `HttpRequestException`, as the result predicates within Polly are not evaluated if an exception is thrown.  Hence my request for a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve), or to see more code.  It may be that the combination of policies you have expressed - or some other code manipulating the result - is causing a null result to be returned to one of the policies. Hard to tell without seeing more code.

**Comment by reisenberger** [comment]
@abdulwaheed05 Do you need any more help or did you resolve?  Looking at the stack trace:

    System.NullReferenceException: Object reference not set to an instance of an object.
    X:\bt\1011566\repo\src\Common\Gateway\GatewayService\PolicyProvider.cs:line 73
    at System.Linq.Enumerable.Any[TSource](IEnumerable1 source, Func2 predicate)
    at Polly.CircuitBreaker.CircuitBreakerEngine.d__11.MoveNext() in C:\projects\polly\src\Polly.Shared\CircuitBreaker\CircuitBreakerEngineAsync.cs:line 48 

it is clear the predicate `r.StatusCode == HttpStatusCode.ServiceUnavailable` is throwing the `NullReferenceException`, so must be `r == null`. So the code executed through the circuit-breaker must be receiving a `null` result.  

Happy to help if you can share more code, otherwise I'll close this.

**Comment by abdulwaheed05** [comment]
@reisenberger sorry i got busy with work. Yes i need help i will submit a working repro soon.

Thanks for your help.

**Comment by reisenberger** [comment]
Closing due to inactivity. However, we will very gladly reopen if you do need further assistance - just post here to let us know.
