### ISSUE TITLE
Occasionally ObjectDisposedException Thrown retrying `Microsoft.Azure.Devices.AmqpServiceClient.SendAsync(...)`

### ISSUE THREAD

**Issue by PanClifton** [App-vNext/Polly#646]
Hello 

For some reason i am occasionally experiencing following exception:

```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'AmqpBodyStreamMessage'.
at Microsoft.Azure.Devices.AmqpServiceClient.SendAsync(String deviceId, Message message, Nullable`1 timeout)
at Polly.RetrySyntaxAsync.<>c__DisplayClass21_1.<<WaitAndRetryAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at Polly.Retry.RetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory, Boolean continueOnCapturedContext)
--- End of inner exception stack trace ---
at ABB.Ability.Cloud.DCS.Core.RetryPolicies.RetryPolicyConfigurations.RetryPolicyConfigurator.<>c__DisplayClass3_0.<SetIotHubRetryPolicy>b__3(Exception ex, TimeSpan delay, Int32 retries, Context context) in D:\\a\\1\\s\\ABB.Ability.Cloud.DCS.Core\\RetryPolicies\\RetryPolicyConfigurations\\RetryPolicyConfigurator.cs:line 147
at Polly.RetrySyntaxAsync.<>c__DisplayClass20_0.<<WaitAndRetryAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at Polly.Retry.RetryStateWaitAndRetry`1.CanRetryAsync(DelegateResult`1 delegateResult, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
at Polly.Retry.RetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory, Boolean continueOnCapturedContext)
at Polly.Policy.ExecuteAsyncInternal(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
at ABB.Ability.Cloud.DCS.PlatformMessageSender.MessageSenderService.TryPublishDeviceMessageToIotHubAsync(Message deviceMessage, String deviceId, Message message) in D:\\a\\1\\s\\ABB.Ability.Cloud.DCS.PlatformMessageSender\\MessageSenderService.cs:line 139 Cannot access a disposed object.
Object name: 'AmqpBodyStreamMessage'.
```

I have already spoke with Microsoft regarding Microsoft.Azure.Devices.ServiceClient and they directed me to you saying quote '**I have reviewed the code sample you sent and I think this may be a race condition inside the Polly package that is causing the object to fall out of scope and be disposed prior to a response being
receive**d.'

Do you know what may cause this behavior?

My code is as follows

// service
```
 public class IotHubService
    {
        private readonly Microsoft.Extensions.Logging.ILogger<IotHubService> _logger;
        private readonly IIotHubConfiguration _iotHubConfiguration;
        private ServiceClient _serviceClient;
        private readonly IAsyncPolicy _retryPolicy;

        public IotHubService(Microsoft.Extensions.Logging.ILogger<IotHubService> logger,
            IIotHubConfiguration iotHubConfiguration,
            IAsyncPolicy retryPolicy)
        {
            _logger = logger;
            _iotHubConfiguration = iotHubConfiguration;
            _retryPolicy = retryPolicy;

            CreateServiceClient();
        }

        public void CreateServiceClient()
        {
            _serviceClient = ServiceClient.CreateFromConnectionString(
                _iotHubConfiguration.OwnerConnectionString,
                _iotHubConfiguration.TransportType);
        }

        public Task SendAsync(string deviceId, Message message)
        {
            return _retryPolicy.ExecuteAsync(
                _ =>
                {
                    return _serviceClient.SendAsync(deviceId, message, _iotHubConfiguration.MessagingOperationTimeout);
                },
                new Context()
                {
                    {nameof(IIotHubService), this},
                    {nameof(Message), message},
                    {ConstantsSettings.RetryPolicies.Polly.ContextLoggerKey, _logger}
                });
        }
    }
```
//retry policy
```
  private static void SetIotHubRetryPolicy(IServiceCollection services, IConfigurationSection section)
        {
            if (section?.Exists() == false) return;

            var policyOptions = section.Get<IotHubRetryPolicyOptions>();
            services.Configure<IotHubRetryPolicyOptions>(section);

            var policyRegistry = services.AddPolicyRegistryIfNotExists();

            policyRegistry.Add(
                ConstantsSettings.RetryPolicies.Polly.IotHubRetry,
                Policy.Handle<IotHubCommunicationException>()
                    .Or<IotHubThrottledException>()
                    .Or<DeviceMaximumQueueDepthExceededException>()
                    .Or<IotHubSuspendedException>()
                    .Or<TimeoutException>()
                    .Or<IotHubException>(ex => ex.IsTransient)
                    .WaitAndRetryAsync(
                        policyOptions.Retry.Count,
                        retryAttempt => TimeSpan.FromSeconds(Math.Pow(policyOptions.Retry.BackoffPower, retryAttempt)),
                        (ex, delay, retries, context) =>
                        {
                            string correlationId = string.Empty;

                            if (context.TryGetValue(nameof(Message), out object message))
                                correlationId = ((Message)message).CorrelationId;

                            if (context.TryGetLogger<ILogger<IotHubService>>(out var logger))
                            {
                                logger.Warn(correlationId,
                                    $"IoT Hub transient error detected ({ex.GetType().Name}), retrying {retries} time after {delay.Seconds} seconds delay... ");
                            }

                            if (retries == policyOptions.Retry.Count)
                            {
                                // Temporary fix until bug https://github.com/Azure/azure-iot-sdk-csharp/issues/613 will be resolved
                                if (ex is TimeoutException && context.TryGetValue(nameof(IIotHubService), out object service))
                                {
                                    try
                                    {
                                        logger.Info(correlationId, "Trying to reestablish underlying IoT Hub AMQP connection...");
                                        ((IIotHubService)service).CreateServiceClient();
                                        logger.Info(correlationId, "IoT Hub service client re-created.");
                                    }
                                    catch (Exception e)
                                    {
                                        const string error = "Error reestablishing AMQP connection";
                                        logger.Error(e, correlationId, error);
                                        throw new TransientException(e, error);
                                    }
                                }
                                else
                                {
                                    throw new TransientException(ex, "IoT Hub transient error detected");
                                }
                            }
                        }
                    )
               );
        }

```
// end

**Comment by reisenberger** [comment]
Thanks @PanClifton . I think the advice you have received ("this may be a race condition inside the Polly package") is a red herring. 

Just googling the error message  returns (as top result for me) https://github.com/Azure/azure-iot-sdk-csharp/issues/7, where users have reported an identical issue on the Azure iot/amqp repo with similar characteristics (sporadic), independent of Polly.

The Polly retry policy _itself_ could only intrinsically be responsible for creating race conditions (independent of the code executed through it) if it was spinning off tasks with `Task.StartNew(...)` or similar (it doesn't) or failing to `await` async methods it calls (it doesn't; the relevant awaits are [here](https://github.com/App-vNext/Polly/blob/57a82e8e43e23935778aef8a944b88d17ccf0cc7/src/Polly.Shared/Retry/RetryStateWaitAndRetryAsync.cs#L28) and [all through here](https://github.com/App-vNext/Polly/blob/57a82e8e43e23935778aef8a944b88d17ccf0cc7/src/Polly.Shared/Retry/RetryEngineAsync.cs#L29-L56)). Everything Polly retry does is linear, with `await`, on the caller's call path. 

_Using_ a Polly retry policy could create race conditions if _the code executed through the policy_ (either the delegate passed to `ExecuteAsync(...)` or the `onRetryAsync` delegate) introduces concurrency or, eg, fails to `await` async methods:

+ _Your_-authored code as posted above looks safe to me in this respect.  
+ The method `IotHubService.SendAsync(...)` has async-await elision twice. We use async-await elision a lot also in Polly and I read your usage as safe. [Stephen Cleary's blog on async-await elision](https://blog.stephencleary.com/2016/12/eliding-async-await.html) is a good reference. 
+ Calls (not shown) to `IotHubService.SendAsync(...)`, are they  `await`-ed?
+ I noticed the code after comment `// Temporary fix until` doesn't dispose the previous `_serviceClient` (it is an `IDisposable`).  Could this cause a resource leak? (independent of whether connected to the issue raised).

Given https://github.com/Azure/azure-iot-sdk-csharp/issues/7 and our confidence Polly retry is not an intrinsic source of race conditions, I think it's reasonable for me to direct you back to the MS iot/amqp teams on this.

Hope some of this is helpful.

**Comment by reisenberger** [comment]
Hi @PanClifton Is there anything further we can help with on this?

**Comment by PanClifton** [comment]
Hi @reisenberger, sorry for late response, i was on holidays. 
We resolved issue. 
There was nothing wrong with retry policies. We had to clone Microsoft.Azure.Devices.Client.Message on second send try because Microsoft.Azure.Devices.Client SDK disposed it on first try.

Thank You for your help.
