### ISSUE TITLE
don't retry if validation exception

### ISSUE THREAD

**Issue by Logi-Fy-Pravin** [App-vNext/Polly#904]
I am using Polly for .Net Core. I am trying to skip retrying when validation exception but still getting some unusual exception in other format and global exception handling is also not showing exception in correct format.

```
Domain.Validation.ValidationException: Validation Error(s)
   at Infrastructure.NoSql.CosmosDb.Company.CommandHandlers.CreateCommandHandler.Handle(CreateCommand request, CancellationToken cancellationToken) 
   at Polly.AsyncPolicy.<>c__DisplayClass40_0.<<ImplementationAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at MediatR.Mediator.PublishCore(IEnumerable`1 allHandlers, INotification notification, CancellationToken cancellationToken)
   at WebApi.Controllers.CompaniesController.AddAsync(CompanyDto item, CancellationToken cancellationToken) in C:\Projects\ReceiptVoucher\logify.Finance.ReceiptVoucherService\WebApi\Controllers\CompaniesController.cs:line 159
   at lambda_method11(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at WebApi.Extensions.ApiLogging.Invoke(HttpContext httpContext, IMediator mediator) in C:\Projects\ReceiptVoucher\logify.Finance.ReceiptVoucherService\WebApi\Extensions\ApiLogging.cs:line 34
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Accept: */*
Accept-Encoding: gzip, deflate, br
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyTmFtZSI6IlNDMTAwNSIsIlVzZXJHcm91cCI6IjY5ZjJjZDQyLWI2YTQtNDE4Zi1hNGMyLWVjZTNkNzE5ZWQ2ZiIsIlVzZXJWaXNpYmlsaXR5IjoiOWU4Y2Y5NjAtZjk4ZC00OWZhLTk2YWYtNjBjMWY4OGI1OGY4IiwiU2hvd0xvY2FsTGFuZ3VhZ2UiOiIiLCJGdWxsTmFtZSI6IlByYXZpbiBZYWRhdiIsImV4cCI6MTYzODYyNzk3MywiaXNzIjoiaHR0cHM6Ly9hcGkuZGV2LnVzZXIubG9naS1meS5jb20vIiwiYXVkIjoiTG9naWZ5In0.PNh0kuBE2U6kbqg6DAC3fVlHdPnbaq1fXkCy0V-XFdU
Connection: keep-alive
Content-Length: 853
Content-Type: application/json
Host: localhost:44347
User-Agent: PostmanRuntime/7.28.4
Session: 11dd55a7-8297-49b1-ac93-b95fe31f0467
Postman-Token: cea5774a-931c-470f-bb5e-61837063da75
```

**Comment by martincostello** [comment]
Without seeing the code for your Polly usage, there's not much to go on here for us to help you.

Also the request headers youve posted in the issue body contain a JWT. You should avoid posting such authentication tokens in public as they may present a security risk.

**Comment by Logi-Fy-Pravin** [comment]
Hi @martincostello 

Please find below code snipped for your ready reference. I just want to raise validation exception in user defined ApiResponse object and do not retry if validation exceptions are occurred.

**Global Exception Handler:**
`
        app.UseExceptionHandler(options =>
        {
            options.Run(async context =>
            {
                context.Response.ContentType = "application/json";
                var ex = context.Features.Get<IExceptionHandlerFeature>();
                if (ex != null)
                {
                    ApiResponse err = new ApiResponse();
                    if (ex.Error is ValidationException)
                    {
                        context.Response.StatusCode = (int)HttpStatusCode.BadRequest;
                        var valErros = new List<ValidationError>();
                        foreach (var vError in ((ValidationException)ex.Error).Errors) { valErros.Add(new ValidationError() { ErrorMessage = vError.Message, MemberName = vError.Context }); }
        
                        err = new ApiResponse()
                        {
                            Ok = false,
                            Error = false,
                            ResponseCode = HttpStatusCode.BadRequest,
                            IsValidationError = true,
                            ValidationErrors = new ValidationErrors() { Errors = valErros }
                        };
                    }
                    else
                    {
                        context.Response.StatusCode = (int)HttpStatusCode.InternalServerError;
                        err = new ApiResponse()
                        {
                            Ok = false,
                            Error = true,
                            ResponseCode = HttpStatusCode.BadRequest,
                            IsValidationError = false,
                            Errors = new ErrorViewModel() { ErrorCode = new ErrorCodes() { Message = ex.Error.Message, Description = ex.Error.StackTrace }, ErrorLog = new ErrorLog() { Message = ex.Error.Message, Description = ex.Error.StackTrace } }
                        };
                    }
                    await context.Response.WriteAsync(err?.ToString()).ConfigureAwait(true);
                }
            });
        });
`
**Polly Decorator:**
`

        public RetryDecorator(MediatR.INotificationHandler<TNotification> inner)
                {
                    _inner = inner; 
                    _retryPolicy = Policy.Handle<ArgumentOutOfRangeException>()
                        .WaitAndRetryAsync(3,
                            i => TimeSpan.FromSeconds(i));
        
                }
        
                public Task Handle(TNotification notification, CancellationToken cancellationToken)
                {
                    return _retryPolicy.ExecuteAsync(() => _inner.Handle(notification, cancellationToken));
                }
`
**Command Handler:**
` 
          public async Task Handle(CreateCommand request, CancellationToken cancellationToken)
                  {
                      var validationErrors = await _repository.ValidateAsync(request, cancellationToken);
                      if (validationErrors != null && validationErrors.Any())
                          throw new Domain.Validation.ValidationException("Validation Error(s)", validationErrors.ToArray());
          
                      var itemExist = await _repository.IsExistAsync(request, cancellationToken);
                      if (itemExist == true)
                          throw new Domain.Validation.ValidationException("Duplicate Record Error");
                  }
`

**Comment by Logi-Fy-Pravin** [comment]
@martincostello Sir, any update?

**Comment by martincostello** [comment]
Sorry, I've been busy today and this past weekend. I'll aim to take a proper look for you tomorrow.

**Comment by martincostello** [comment]
I don't really see where the question you're asking applies here.

You're only retrying on `ArgumentOutOfRangeException` so it wouldn't retry `ValidationException`, _unless_ that exception type derives from `ArgumentOutOfRangeException` (but I can't tell from the code you've posted).

If it does, then use the `Handle<T>()` overload that takes a predicate, and require that the exception is an `ArgumentOutOfRangeException` but is not a `ValidationException`.

```csharp
Policy.Handle<ArgumentOutOfRangeException>(ex => ex is not ValidationException);
```

**Comment by Logi-Fy-Pravin** [comment]
Hi @martincostello 

Below is Validation Exception, is there any clue on this, as I only want to not retry when validation exception.
```

          public class ValidationException : Exception
          {
              public ValidationException(string message) : this(message, null) { }
              public ValidationException(string message, params ValidationError[] errors) : base(message, null)
              {
                  this.Errors = errors ?? Enumerable.Empty<ValidationError>();
              }
      
              public IEnumerable<ValidationError> Errors { get; private set; }
      
          }

```

you can see below stack trace as Validation Exception is raising but Polly retrying many times:

```
Domain.Validation.ValidationException: Validation Error(s)
   at Infrastructure.NoSql.CosmosDb.Company.CommandHandlers.CreateCommandHandler.Handle(CreateCommand request, CancellationToken cancellationToken) 
   at Polly.AsyncPolicy.<>c__DisplayClass40_0.<<ImplementationAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---

```

**Comment by martincostello** [comment]
Do you have any observable proof that `ValidationException` is causing retries?

You have not configured the policy to do so, and its presence in the stack trace does not imply it is performing retries, just that calls are being executed _through_ the policy, which is by design.

**Comment by Logi-Fy-Pravin** [comment]
Hi @martincostello, Thanks for your advice and sorry for wasting your time. You are right, issue was in ApiLogging Middleware, I was confused due to stack trace showing Polly.MoveNext().

Thanks & sorry once again !!
