### ISSUE TITLE
TimeoutAsync does not propegate the correct cancellation token

### ISSUE THREAD

**Issue by rick-palmsens** [App-vNext/Polly#934]
**Summary**: 
When cancelling the execution of a timeout policy and then catching the operation cancelled exception, the cancellation token in the exception does not match the one that was cancelled. This makes it impossible to check which cancellation token triggered the exception.

**Expected behavior**: 
`OperationCanceledException.CancellationToken` should equal the input cancellation token.

**Actual behaviour**:
`OperationCanceledException.CancellationToken` does not equal the input cancellation token.

**Steps / Code to reproduce the problem**: 
```csharp
using System.Diagnostics;
using Polly;
using Polly.Timeout;

namespace PollyBug
{
    public class Program
    {
        public static async Task Main(string[] args)
        {
            // Create an async timeout policy
            var timeoutPolicy = Policy.TimeoutAsync(TimeSpan.FromSeconds(10), TimeoutStrategy.Optimistic);

            // Create a cancellation token
            var cancellationTokenSource = new CancellationTokenSource();
            var cancellationToken = cancellationTokenSource.Token;

            // Execute the timeout policy with a cancellable task
            var task = timeoutPolicy.ExecuteAsync(c => Task.Delay(TimeSpan.FromSeconds(10), c), cancellationToken);

            // Cancel the task
            cancellationTokenSource.Cancel();

            try
            {
                // Await the task to throw the cancellation exception
                await task;
            }
            catch (OperationCanceledException exception)
            {
                // The cancellation tokens do not match!
                Debug.Assert(exception.CancellationToken == cancellationToken);
            }
        }
    }
}
```

**Stack trace**:
```
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Polly.AsyncPolicy.<>c__DisplayClass40_0.<<ImplementationAsync>b__0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Polly.Timeout.AsyncTimeoutEngine.<ImplementationAsync>d__0`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Polly.Timeout.AsyncTimeoutEngine.<ImplementationAsync>d__0`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Polly.AsyncPolicy.<ExecuteAsync>d__12.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PollyBug.Program.<Main>d__0.MoveNext() in C:\Users\Rick\source\repos\PollyBug\Program.cs:line 27
```

**Comment by martincostello** [comment]
Do you have a stack trace for the `OperationCanceledException` that shows exactly where it's being thrown from in your repro?

**Comment by rick-palmsens** [comment]
@martincostello Added the stack trace

**Comment by rick-palmsens** [comment]
The example you gave though explicitly makes sure that the user receives its own cancellation token back:

https://github.com/dotnet/runtime/blob/0e3c8f046b2e8de10507d8d55ad67f20776124b7/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs#L598-L602

**Comment by DaRosenberg** [comment]
@rick-palmsens not sure if this is still on your radar, but some renewed discussions on this in #3086, in case you want to chime in.
