### ISSUE TITLE
How to throw final error using WaitAndRetry and Execute?

### ISSUE THREAD

**Issue by RachelXGanon** [App-vNext/Polly#938]
I'm, trying to check a simple WaitAndRetry of Polly

```
class Program
{
    public static void Main()
    {
           
        int i = 0;
        var _retryPolicy = Policy
       .Handle<Exception>()
        .WaitAndRetry(Backoff.ExponentialBackoff(TimeSpan.FromSeconds(2), 10),
           (exception, timespan) =>
           {
               Console.WriteLine($"Retry: {timespan}. \n ex: {exception}");
           });

        _retryPolicy.Execute(() =>
        {
            Console.WriteLine(i);
            i++;
            int.Parse("something");
        });

        Console.ReadLine();
    }
}   
```
And I want to throw a final exception after all the retries are failed. How can I do it?

**Excepted Result:**

Retry: ..

Retry: ..

Retry: ..

My new final error!
**Actual Result:**
Retry: ..

Retry: ..

Retry: ..
Thank You!

**Comment by martincostello** [comment]
I just turned your example into a xunit test, but with less wait/retry as otherwise it takes a very long time to run (1 second, doubling 10 times) and it behaves as your use case expects.

The operation is tried 5 times, and on the 5th attempt the `FormatException` is thrown.

### Test

```csharp
using System;
using Polly.Contrib.WaitAndRetry;
using Xunit;
using Xunit.Abstractions;

namespace Polly.Specs.RateLimit;

public class Issue938
{
    private readonly ITestOutputHelper _outputHelper;

    public Issue938(ITestOutputHelper outputHelper)
    {
        _outputHelper = outputHelper;
    }

    [Fact]
    public void Fail_Repeatedly()
    {
        int i = 0;

        var _retryPolicy = Policy
           .Handle<Exception>()
            .WaitAndRetry(Backoff.ExponentialBackoff(TimeSpan.FromSeconds(0.05), 5),
               (exception, timespan) =>
               {
                   _outputHelper.WriteLine($"Retry: {timespan}. \n ex: {exception}");
               });

        _retryPolicy.Execute(() =>
        {
            _outputHelper.WriteLine(i.ToString());
            i++;
            int.Parse("something");
        });
    }
}
```

### Test Output

```
 Polly.Specs.RateLimit.Issue938.Fail_Repeatedly
   Source: Issue938.cs line 18
   Duration: 1.6 sec

  Message: 
System.FormatException : Input string was not in a correct format.

  Stack Trace: 
Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
Int32.Parse(String s)
<>c__DisplayClass2_0.<Fail_Repeatedly>b__1() line 34
<>c__DisplayClass108_0.<Execute>b__0(Context _, CancellationToken _) line 18
<>c__DisplayClass138_0.<Implementation>b__0(Context ctx, CancellationToken token) line 18
RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider) line 35
RetryPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken) line 35
Policy.Implementation(Action`2 action, Context context, CancellationToken cancellationToken) line 18
Policy.Execute(Action`2 action, Context context, CancellationToken cancellationToken) line 73
Policy.Execute(Action action) line 18
Issue938.Fail_Repeatedly() line 30

  Standard Output: 
0
Retry: 00:00:00.0500000. 
 ex: System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Int32.Parse(String s)
   at Polly.Specs.RateLimit.Issue938.<>c__DisplayClass2_0.<Fail_Repeatedly>b__1() in C:\Coding\App-vNext\Polly\src\Polly.Specs\RateLimit\Issue938.cs:line 34
   at Polly.Policy.<>c__DisplayClass108_0.<Execute>b__0(Context _, CancellationToken _) in C:\Coding\App-vNext\Polly\src\Polly\Policy.ExecuteOverloads.cs:line 18
   at Polly.Policy.<>c__DisplayClass138_0.<Implementation>b__0(Context ctx, CancellationToken token) in C:\Coding\App-vNext\Polly\src\Polly\Policy.SyncNonGenericImplementation.cs:line 18
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider) in C:\Coding\App-vNext\Polly\src\Polly\Retry\RetryEngine.cs:line 35
1
Retry: 00:00:00.1000000. 
 ex: System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Int32.Parse(String s)
   at Polly.Specs.RateLimit.Issue938.<>c__DisplayClass2_0.<Fail_Repeatedly>b__1() in C:\Coding\App-vNext\Polly\src\Polly.Specs\RateLimit\Issue938.cs:line 34
   at Polly.Policy.<>c__DisplayClass108_0.<Execute>b__0(Context _, CancellationToken _) in C:\Coding\App-vNext\Polly\src\Polly\Policy.ExecuteOverloads.cs:line 18
   at Polly.Policy.<>c__DisplayClass138_0.<Implementation>b__0(Context ctx, CancellationToken token) in C:\Coding\App-vNext\Polly\src\Polly\Policy.SyncNonGenericImplementation.cs:line 18
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider) in C:\Coding\App-vNext\Polly\src\Polly\Retry\RetryEngine.cs:line 35
2
Retry: 00:00:00.2000000. 
 ex: System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Int32.Parse(String s)
   at Polly.Specs.RateLimit.Issue938.<>c__DisplayClass2_0.<Fail_Repeatedly>b__1() in C:\Coding\App-vNext\Polly\src\Polly.Specs\RateLimit\Issue938.cs:line 34
   at Polly.Policy.<>c__DisplayClass108_0.<Execute>b__0(Context _, CancellationToken _) in C:\Coding\App-vNext\Polly\src\Polly\Policy.ExecuteOverloads.cs:line 18
   at Polly.Policy.<>c__DisplayClass138_0.<Implementation>b__0(Context ctx, CancellationToken token) in C:\Coding\App-vNext\Polly\src\Polly\Policy.SyncNonGenericImplementation.cs:line 18
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider) in C:\Coding\App-vNext\Polly\src\Polly\Retry\RetryEngine.cs:line 35
3
Retry: 00:00:00.4000000. 
 ex: System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Int32.Parse(String s)
   at Polly.Specs.RateLimit.Issue938.<>c__DisplayClass2_0.<Fail_Repeatedly>b__1() in C:\Coding\App-vNext\Polly\src\Polly.Specs\RateLimit\Issue938.cs:line 34
   at Polly.Policy.<>c__DisplayClass108_0.<Execute>b__0(Context _, CancellationToken _) in C:\Coding\App-vNext\Polly\src\Polly\Policy.ExecuteOverloads.cs:line 18
   at Polly.Policy.<>c__DisplayClass138_0.<Implementation>b__0(Context ctx, CancellationToken token) in C:\Coding\App-vNext\Polly\src\Polly\Policy.SyncNonGenericImplementation.cs:line 18
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider) in C:\Coding\App-vNext\Polly\src\Polly\Retry\RetryEngine.cs:line 35
4
Retry: 00:00:00.8000000. 
 ex: System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Int32.Parse(String s)
   at Polly.Specs.RateLimit.Issue938.<>c__DisplayClass2_0.<Fail_Repeatedly>b__1() in C:\Coding\App-vNext\Polly\src\Polly.Specs\RateLimit\Issue938.cs:line 34
   at Polly.Policy.<>c__DisplayClass108_0.<Execute>b__0(Context _, CancellationToken _) in C:\Coding\App-vNext\Polly\src\Polly\Policy.ExecuteOverloads.cs:line 18
   at Polly.Policy.<>c__DisplayClass138_0.<Implementation>b__0(Context ctx, CancellationToken token) in C:\Coding\App-vNext\Polly\src\Polly\Policy.SyncNonGenericImplementation.cs:line 18
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider) in C:\Coding\App-vNext\Polly\src\Polly\Retry\RetryEngine.cs:line 35
5
```
